# AwaNet Render Deployment Plan

services:
  - name: AwaNet-Backend
    type: web_service
    env: python
    repo: https://github.com/Hemi-Whiro22/AwaNet-autoDeploy.git
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      SUPABASE_URL: <your-supabase-url>
      SUPABASE_KEY: <your-service-role-key>
      OPENAI_API_KEY: <your-openai-key>
      BUCKET_NAME: kaitiaki_taonga

staticSites:
  - name: AwaNet-React
    repo: https://github.com/Hemi-Whiro22/AwaNet-autoDeploy.git
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      VITE_API_URL: https://awanet-backend.onrender.com
